### ISSUE TITLE
公告显示不出来

### ISSUE THREAD

**Issue by lniuua** [CokeSR/Hk4e-SDK#10]
![2 C4D8H6BAOV }C UE6CY4M](https://github.com/user-attachments/assets/883ee114-c1f9-4d9c-a59c-9ff848553da3)
![QQ图片20240818191830](https://github.com/user-attachments/assets/990c8db2-17da-4f44-b467-58306ae3000a)
是还需要改些什么吗

**Comment by CokeSR** [comment]
代理问题，检查路由是否正确












Coke
***@***.***


---Original---
From: ***@***.***&gt;
Sent at: 2024年8月18日(Sun) Evening7:20
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [CokeSR/Hk4e-SDK] 公告显示不出来 (Issue #10)




 
2.C4D8H6BAOV.C.UE6CY4M.png (view on web)
 QQ.20240818191830.jpg (view on web)
 是还需要改些什么吗
